# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4b16b37bea93f4a4349d631d5812444cf9dc12b0a0daa26cbea42397711dc48a918fd56d8698c9dab378f71fbbc42bf121ca200927251a076a7f031edc4e189

test:
  secret_key_base: 71c1c2fe9ba5b9ccb159fdf18f7b50d923245d8d1d0d7175f4479ac4e67042c1270c39bf5052976fdde69dbb5e334b863e2303622e83317206212ae15d1e6aa1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
